### ISSUE TITLE
Accessing secret variables from release task

### ISSUE THREAD

**Issue by apucacao** [Microsoft/vsts-task-lib#185]
Hello,

We have built a VSTS extension that adds UI to the work item dialog, and a task to update some state in our application.

The rollout task reads a few inputs like `release.releaseId` and `System.TeamProjectId`. It also expects the user to set some variables so that the task can make authenticated calls to VSTS. One such call fetches the work items associated with a release via the Release API.

The authentication currently only works with alternate credentials or PAT. So the user needs to set `username` and `password` variables on the release. The task then reads them via `getVariable`. The code looks something like this:

```
var https = require('https');
var tl = require('vso-task-lib/vsotask');
var username = tl.getVariable('username', false);
var password = tl.getVariable('password', false);
var auth = username + ':' + password;

https.request({..., auth: auth}, function(res) {
  ...
});
```

The issue we're running into is that the password variable is `undefined` if it is made secret in the UI, and authenticated VSTS calls fail.

Is there a separate method we can use to read secret variables?

Best,

Alexis

**Comment by apucacao** [comment]
I forgot to mention that we're using `vsts-task-lib` version 0.5.11.

**Comment by ericsciple** [comment]
you can use getEndpointAuthorizationParameter('SystemVssConnection', 'AccessToken') to access the job token

i believe a 2x agent (2.105.7 would be a good backstop - i.e. TFS 2017 RTM agent) is required in order access secret variables.

if using the job token is not good for your scenario, then i would suggest switching to an input instead of relying on user to set a specific variable. then the user can pass their secret variable into the input - e.g. `$(myusername)`

**Comment by apucacao** [comment]
Thanks @ericsciple, I can try that. One question though: how do I pass the job token along with request to VSTS? Do I need to set a header? Currently we're using basic authentication.

**Comment by ericsciple** [comment]
i think you can pass it as the password. you may need to pass some dummy value for the username (e.g. abc). also i would recommend using bearer instead of basic since it does not require basic to be enabled for tfs on-prem installations.

also, i'm not familiar with the details, but you could also see what the [nuget task](https://github.com/Microsoft/vsts-tasks/blob/0d4a83fa08f99008eee500860b944f197c8af63b/Tasks/NuGetInstaller/nugetinstaller.ts) does and use that as a go-by.

**Comment by ericsciple** [comment]
...if you use the nuget task as a go-by, look for `getSystemAccessToken`

**Comment by bryanmacfarlane** [comment]
You need to set the bearer header

https://github.com/Microsoft/vsts-node-api/blob/master/api/handlers/bearertoken.ts

If you use node api, you can construct it with that auth handler.
