### ISSUE TITLE
Variables set by setVariable are not visible in the Finalize build phase

### ISSUE THREAD

**Issue by PeterStaev** [Microsoft/vsts-task-lib#193]
I'm using [this](https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-variable-tasks) extension to transform some variables in a better format. The developer is using `tl.setVariable` to set those variables (for example [here](https://github.com/jessehouwing/vsts-variable-tasks/blob/master/vsts-variable-set/vsts-variable-set.ts#L11)). Those variables work fine in the build phase, but  are not visible in the Finalize build phase. For example I'm initializing a `Label` variable. When I use it in the build process it shows the correct value. But if I set to label sources on successful build with `$(Label)` the variable is not expanded and sources are labeled with the `$(Label)` and not its value.

**Comment by ericsciple** [comment]
This is currently by design (and not related to the task lib repo). Docs about labeling [are here](https://www.visualstudio.com/en-us/docs/build/define/variables)

"Apply a version control label during the build process ... Predefined, agent scope: No"

Labeling happens server side. After a build, the variables aren't sent back up to the server.

`##vso[build.updatebuildnumber]build number` might be the correct solution? refer [commands](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md)

Let me know. If so it may be good to update the docs.

**Comment by PeterStaev** [comment]
I understand. And yes, this is how I overcome the problem currently - I set the custom format to the build number as the extension uses `updateBuildNumber` and then for the labeling I use `$(Build.BuildNumber)` .

**Comment by ericsciple** [comment]
@PeterStaev thanks for confirmation. I'll fwd this thread along to appropriate folks. We might be missing some scenario guidance in our docs. It feels like questions about this come up in issues a lot.
