### ISSUE TITLE
Verbose pipeline getting dropped when running ad hoc script from PowerShell task

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-task-lib#206]
Fixed by PR: https://github.com/Microsoft/vsts-task-lib/pull/201

**Comment by ericsciple** [comment]
(affects AzurePowerShell task)

**Comment by hrboyceiii** [comment]
@ericsciple this was very hard to discover given it's undocumented.  If I had not cross referenced the changes to AzurePowerShell Task in the other repo I wouldn't have found the "fix".

What's the recommendation here?  We have a number of tasks that either dot source scripts or otherwise reference files and the verbose output is/was dropped.  It's unfortunate that the colored formatting is also not preserved. Is the preferred approach to use modules and import them rather than dot sourcing?

I appreciate the help!
