### ISSUE TITLE
Including external tool

### ISSUE THREAD

**Issue by rosieks** [Microsoft/vsts-task-lib#284]
Hi,
I would like to create task that will run some node tool using ToolRunner, but first I want to install that tool. Is there any way to run `npm install -g mytool` as part of the extension installation or is there any guideline how to deal with installing/shipping 3rd party tools with VSTS extension?

**Comment by bryanmacfarlane** [comment]
npm install is a build time action for the developer.  The produced task package should carry everything it needs (including packages and tools).  For example in our [tasks](https://github.com/Microsoft/vsts-tasks) we pull tools from blob storage during build and run npm install during the build.

Be careful of OS dependencies in tools you carry.  For example, a task that calls a tool in java or netcore both have OS dependencies.  Your task should guard against that and check at runtime since consumer will just install your task from the market place and expect it to work.
