### ISSUE TITLE
Issue with git tagging

### ISSUE THREAD

**Issue by AceHack** [Microsoft/vsts-task-lib#366]
I'm running into the same issue as posted here

https://developercommunity.visualstudio.com/content/problem/91058/tag-sources-not-working-with-custom-variable.html

I've tried using the workaround described using the Git Tag task from here
https://github.com/ReneSorensen/VSTSTools

But that freezes and never completes on the git push.

I've also tried using a yaml build and just running the git tag command manually, it has the same freezing problem.

Thanks.

**Comment by AceHack** [comment]
FYI I also tried updating the $(build.buildNumber) in a script and while that worked it caused other issues like VSTS starts forgetting the revision number of builds and you have build number conflicts because the same revision number is used more than once

**Comment by bryanmacfarlane** [comment]
here's the docs on how to run git scripts (that make changes) as part of your build

https://docs.microsoft.com/en-us/vsts/build-release/actions/scripts/git-commands?view=vsts 

It's hanging because git is prompting for credentials.  

Specifically, if you check this option we will give your scripts access to the bearer token and git commands that need security will just work.  That bearer token is per build for security reasons.

https://docs.microsoft.com/en-us/vsts/build-release/actions/scripts/git-commands?view=vsts#enable-scripts-to-run-git-commands 

Ensure you give the service account

Your other option is to setup git creds with a credential provider but that's much less secure because it gives standing access to anything that happens to run on that agent.

**Comment by damccorm** [comment]
@AceHack looks like this has been resolved so I'm going to close. Feel free to reopen if appropriate.
