### ISSUE TITLE
Cannot find module "..."

### ISSUE THREAD

**Issue by apucacao** [Microsoft/vsts-task-lib#59]
Hello,

I was testing my node task to make sure it worked on the hosted agents, and was getting a "Cannot find module 'vso-task-lib'". I was using relative paths (`var tl = require('../../../../node_modules/vso-task-lib');
`) and that worked on my local agent, but not on the hosted one.

I have 2 questions:

1. I found an article that recommended that the task lib be installed in the task folder; so the task folder now has a `node_modules` directory with the library and anything that the task requires. Is this the way to go?
2. Was `vso-task-lib` renamed to `vsts-task-lib`?

Thanks!

Alexis

**Comment by ericsciple** [comment]
1) Yes. https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/vsts-task-lib.md
2) Yes.

**Comment by myermian** [comment]
I realize that this issue is closed, but I have a related question. My extension works when I include node_modules/* in the same folder as my task.

My question is if there is a way for typescript to drop in only those modules which are required for that task. It seems a bit overkill to include all the JS, TS, and readme files. Do I only need the *.js files to be packaged up or the *.ts files or both? And if I only need the *.js files, how can I make it so that during my typescript compilation or packaging it pulls in only the files necessary?
